### PR TITLE
SOCOM Series Discord RPC

### PR DESCRIPTION
**Pull request by xCENTx**
- Included SOCOM 1, 2 and 3
- SOCOM 3 is missing team win counters
- SOCOM 1 & 3 don't have map images (for now)
image

### CODE REVIEW

**Comment by Zero1UP** [comment]
Would probably be better to break out each game into it's own file rather than 1 file having all the classes just to keep cleaner. It's not a huge deal but if you don't do it then I probably will. As for the whole checkbox selection, that probably needs to be redone to not need that. We can either pull it from memory or pull it from the title bar in pcsx2. I am thinking that using the CRC might be a good way to do it.

I am also not sure why you are adding in addresses for a version of s2 that isn't supported.

**Comment by xCENTx** [comment]
I removed my branch. Enjoy your SOCOM Series RP. Even tho it was my idea and carried it out. I'll just have my own private version for myself.

**Comment by Zero1UP** [comment]
> 
> 
> I removed my branch. Enjoy your SOCOM Series RP. Even tho it was my idea and carried it out. I'll just have my own private version for myself.

You have some serious problems. Get help.

**Comment by xCENTx** [comment]
Says the guy who messaged me gloating about finally putting work into this project yet still doesnt have the patch 1.4 offsets even tho i graciously handed them out like candy to you

**Comment by Zero1UP** [comment]
> 
> 
> Says the guy who messaged me gloating about finally putting work into this project yet still doesnt have the patch 1.4 offsets even tho i graciously handed them out like candy to you

Gloating? I was telling you that I fixed the problems which I mentioned in this thread. I have no idea what your deal is but you need to get over it.

You made the pull request and I started updating the program so it handles this stuff better. For some reason now you are getting upset over that?

**Comment by xCENTx** [comment]
Bro? You legit messaged me telling me about all the cool things you did right? Updating me? So i follow up with my own update and your  like "OK?" like why even message me to "talk about the program" if you only messaged me to tell me about what you did and have no care in the world to know what i might have done? Like get real bro. and sitting in the SOCOM 1 chat right now telling 2000 people that I'm having a meltdown? Get over yourself bro , it aint that important to me. 


https://i.ibb.co/s5MVcdL/image.png

**Comment by xCENTx** [comment]
> I am also not sure why you are adding in addresses for a version of s2 that isn't supported.

because you had a hissy fit and shut down the PS2 revival servers for everybody forcing people to revert to SVDL and r0005v67r1. Unless yuou dont realise how your actions affect people. This is called being on top of a project and supplying updates as soon as the world around the program updates.

**Comment by Zero1UP** [comment]
> 
> 
> Bro? You legit messaged me telling me about all the cool things you did right? Updating me? So i follow up with my own update and your like "OK?" like why even message me to "talk about the program" if you only messaged me to tell me about what you did and have no care in the world to know what i might have done? Like get real bro. and sitting in the SOCOM 1 chat right now telling 2000 people that I'm having a meltdown? Get over yourself bro , it aint that important to me.
> 
> https://i.ibb.co/s5MVcdL/image.png

I told you how to check what game is running without needing to rely on pulling it from memory.

You sent me a screenshot with no context. I had no idea what I was supposed to be looking for because it looked like what we already had.

You are having a meltdown, you go off the rails acting like a child. Case and point you posting in this thread crying about how I haven't added something when the last update clearly stated it was the start of the re-write.

**Pull request closed without merging**
